### ISSUE TITLE
pip deprecation warning re:scikit-learn

### ISSUE THREAD

**Issue by rafle** [zbw/stwfsapy#45]
Hello, I'm getting the following warning when using pip 23.2 and stwfsapy 0.3.0:

`DEPRECATION: stwfsapy 0.3.0 has a non-standard dependency specifier scikit-learn>=0.24.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of stwfsapy or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
`

**Comment by osma** [comment]
I'm getting the same error when installing stwfsapy 0.3.0 using recent pip.

It seems to me that the problem only applies to the 0.3.0 release, which was released on Oct 18, 2021 [according to PyPI](https://pypi.org/project/stwfsapy/#history). But more recently, this project has switched to Poetry for dependency management, and the scikit-learn dependency is nowadays specified like this, which should be OK: https://github.com/zbw/stwfsapy/blob/831b3bab0a31440cbf128b12612c3f7982d4512f/pyproject.toml#L16

In my understanding, just making a new release (either 0.3.1 or 0.4.0) would fix the problem.

**Comment by cbartz** [comment]
@annakasprzik There is a CI job for publishing, it should be sufficient to just create a tag on the latest master commit if everything is set up correctly in the repo. You can look at Qualle for an example ([here](https://github.com/zbw/qualle/actions/workflows/publish.yml) is the CI workflow from Qualle).
