### ISSUE TITLE
Allow scikit-learn version 1.4.*?

### ISSUE THREAD

**Issue by juhoinkinen** [zbw/stwfsapy#58]
Scikit-learn releases have advanced to [1.4 series](https://github.com/scikit-learn/scikit-learn/releases).

Could you check if stwfsapy could allow upgrading to Scikit-learn 1.4.* ? Now it has pinned scikit-learn to <1.3:

https://github.com/zbw/stwfsapy/blob/7b0d47b4d21c254323f619a1fda53912a9147723/pyproject.toml#L16

This would allow upgrading Scikit-learn to 1.4.* also in Annif.

**Comment by Lakshmi-bashyam** [comment]
Thank for sharing the blog post. I do agree with their stance on upper bounds, at least for minor version. 
While it make sense to follow it now, we have to revisit in case any issues arise.
